- CHANGELOG.rst
- toolium/pageelements/group_page_element.py
- toolium/pageelements/page_element.py
- toolium/pageelements/page_elements.py
- Add support to encapsulated elements (Shadowroot)
| Only support CSS_SELECTOR locator
| It is not supported for list of elements yet
| It is not supported for element find by parent yet
| It is not supported nested encapsulation yet
> Support to encapsulated web elements added

- toolium/behave/env_utils.py
Right now when a dynamic environment fails, the error description is "Failing steps due to precondition exceptions":
```
<error message="Preconditions failed" type="Exception">
<![CDATA[
Failing step: Given get the pi-scope "qa_piscope_roles_2" as "baikal-api", and save it in aws using filename "qa_piscope_roles_2_base" ... failed in 0.000s Location: features/upgrade/base_version.feature:100 Failing steps due to precondition exceptions
]]>
</error>
```
with this fix, the description should add the exception that has failed
> fix: improve dyn envs outputs

- toolium/behave/env_utils.py
Current implementation for dynamic environment failures using `Behave 1.2.6` is not properly managing exit codes in the execution:
```
$ behave
... Steps failed in dyn-env steps ...
...
0 features passed, 1 failed, 0 skipped
0 scenarios passed, 2 failed, 0 skipped
0 steps passed, 2 failed, 0 skipped, 0 undefined, 17 untested
Took 0m0.000s
/app # echo $?
0
```
After this fix, when some step fail in dyn-env (before/after scenario/feature), a hook error will be managed at the end of the execution (after_feature):
```
$behave 
... Steps failed in dyn-env steps ...
...
HOOK-ERROR in after_feature: Exception: Preconditions failed
Failing scenarios:
...
0 features passed, 1 failed, 0 skipped
0 scenarios passed, 2 failed, 0 skipped
0 steps passed, 2 failed, 0 skipped, 0 undefined, 17 untested …
```
> fix: dyn environment for exit codes when hook error is detected

- docs/browser_configuration.rst
- toolium/config_driver.py
Allow for different binary location for Chrome browser. 
Section: Chrome.
Option: binary.
Example in properties.cfg:
```
[Driver]
type: chrome
[Chrome]
binary: /usr/local/chrome_beta/chrome
```
> Support for different binary location for Chrome browser

- toolium/utils.py
Browserstack runs over https servers. Due to hardcore of "http" in Utils.get_server_url, it makes me imposible run tests without mocking this util (in fact it works!), this change will be great ;)
> feat(ssl-remote-server): https for remote servers available using -D Server_ssl=true

- requirements.txt
- toolium/pageelements/page_elements.py
PyCharm marks as warning lines like this:
InputTexts(*locator).page_elements[0].text = "hola"
because it thinks "InputTexts(*locator).page_elements[0]" in instance of "PageElement". The commit patchs this behaveour. Only cosmetics...
> feat(type-hints): Type hint added to page_elements method to avoid fake warnings

- docs/remote_configuration.rst
- docs/tests_result_analysis.rst
- toolium/test/conf/properties.cfg
- Fix typo in documentation for configuration Server logs type
- Wrong documentation lead to invalid config, so toolium will get "all" log type as default
- Related to issuehttps://github.com/Telefonica/toolium/issues/178
> fix: typo in conf Server logs_types -> log_types

- toolium/config_driver.py
- toolium/test/test_config_driver.py
Some Selenoid new capabilities must have type list (for example: hostsEntries). Toolium was converting list values to string and Selenoid can't process them. This PR includes a fix to convert values to list.
> fix: add list type to config driver convert property type method

- CHANGELOG.rst
- toolium/pageelements/page_element.py
- toolium/test/pageelements/test_derived_page_element.py
- toolium/test/pageelements/test_page_element.py
- toolium/test/pageobjects/test_page_object.py
New functionality for mobile tests with webviews. The context will be changed between WEBVIEW and NATIVE automatically.
New config property 'automatic_context_selection' in [Driver] section for mobile tests with webview
- If it's false, the WebElement is searched using always NATIVE context
- If it's true, the WebElement is searched using context NATIVE or WEBVIEW depending of the webview attribute value
Unit tests has been added and executed.
> Nov 224147 automatic context selection

- CHANGELOG.rst
- toolium/pageelements/input_text_page_element.py
Include click() action in inputText element. Sometimes is necessary to show the keyboard for mobile tests.
> Include click action in InputText element

- toolium/pageelements/page_element.py
- toolium/test/pageelements/test_page_element.py
during our tests we have detected that you can have several WEBVIEW contexts (e.g. the app webview context, stetho webview context). Also, the stetho context seems to change index of webview windows depending on the order of the scenarios being run.
Current code does select the first context whose identifier starts with "WEBVIEW". This might lead to selection of webview contexts not belonging to the app and thus, to failures in the selection of the window due to indexes changing. In order to fix this, the appPackage taken from the driver capabilites is added to the string that identifies the WEBVIEW context to be selected
> Manage multiple webviews in mobile devices

- CHANGELOG.rst
- toolium/behave/env_utils.py
Actual behaviour when an error in Dynamic Environment happens:
- **Error in Actions Before Feature:** when this happens all the scenarios are marked as failed (not only the scenarios that matches with the tags)
- **Error in Actions Before each Scenario:** when this happens all the scenarios are marked as failed (not only the scenarios that matches with the tags)
Proposal:
- **Error in Actions Before Feature:** when this happens all the scenarios will be marked as failed (only the scenarios that matches with the tags)
- **Error in Actions Before each Scenario:** when this happens all the scenarios will be marked as failed (only the scenarios that matches with the tags)
> NOV-226397 fix dynamic environment

- toolium/pageelements/input_text_page_element.py
The text getter was not working for android/ios in webview mode. The webview mode check has been added to the get it from value as in web.
> NOV-227875 InputText with webview mode getting the text value

- toolium/test/utils/test_dataset_utils.py
- toolium/utils/dataset.py
Prevent JSON boolean/null from being converted to Python boolean/None
> fix: prevent JSON boolean/null from being converted to Python boolean/None

- .readthedocs.yaml
- CHANGELOG.rst
- README.rst
- docs/requirements.txt
- requirements_dev.txt
* Upgrade Sphinx version from 3.* to 4.*
* Move doc requirements to an specific file
* Add readthedocs configuration in yaml file instead of using default conf
* Update github actions and coverage links to master branch to unify README.rst links
URL to check that readthedocs now works with this PR: https://toolium.readthedocs.io/en/fix-readthedocs/changelog.html
> fix: fix doc compilation errors in readthedocs

- CHANGELOG.rst
- toolium/test/utils/test_poeditor.py
- toolium/utils/poeditor.py
Better handling of the error due to load_poeditor_texts() function being called when POEditor configuration is not available.
> fix: poeditor config not available detection

- CHANGELOG.rst
- toolium/test/utils/test_dataset_replace_param.py
- toolium/utils/dataset.py
resolution of expressions like [TODAY + 1] are now considered, not only if the whole param is the expression but also if the param contains it as part of a longer string.
This change permits the replacement of several placeholders in the same parameter
> chore: resolve datetime offsets within parameters

- CHANGELOG.rst
- docs/bdd_integration.rst
- toolium/test/utils/test_dataset_replace_param.py
- toolium/utils/dataset.py
The placeholder [NOW] and the related one including offsets [NOW +/- offset] can now include a custom format. Here, some examples:
[NOW(%Y-%m-%dT%H:%M:%SZ)]
[NOW(%Y-%m-%dT%H:%M:%SZ) + 10 MINUTES]
[NOW(%Y-%m-%d) - 180 DAYS]
...
> chore: permit custom format for the NOW placeholder

- CHANGELOG.rst
- toolium/test/utils/test_dataset_map_param.py
- toolium/utils/dataset.py
the [CONTEXT:blablabla] does not accept dotted keys if the
element is into the context storage intead of as part of the
context itself. This commit permits searching either in the
context or in the storage by resolving as
context.storage['a'].b.c for a [CONTEXT:a.b.c] key
> feat: search dotted keys into context storage

- CHANGELOG.rst
- toolium/behave/environment.py
- toolium/test/behave/test_environment.py
Ensure the close_drivers method in after_feature is always called. That was not happening when there had been a failure executing the preconditions, due to the exception that is raised in that case.
> fix: ensure close_drivers method is always called in after feature hook

- CHANGELOG.rst
- toolium/pageelements/page_element.py
- toolium/test/pageelements/test_page_element.py
Chromedriver has changed in last versions (from v105), and now windows can not be identified using getContexts method, so automatic context selection for Android has been updated. This change is backward compatible
More info in Appium thread: https://github.com/appium/appium/issues/18906
> NOV-238610: update android automatic context selection

- CHANGELOG.rst
- docs/requirements.txt
Vulnerability fix: https://github.com/readthedocs/readthedocs-sphinx-search/security/advisories/GHSA-xgfm-fjx6-62mj
> fix: upgrade readthedocs-sphinx-search to fix vulnerability

- toolium/test/utils/test_dataset_replace_param.py
- toolium/utils/dataset.py
from the dataset code it seems that support for [STRING_WITH_LENGTH_NN] inside a longer string was inteded to be supported, but the implementation does not work. This is a fix as it might be a useful feature (e.g.: for composing parameters that require a determined substring + having a given length)
> fix: partial replacement for string with length

- CHANGELOG.rst
- toolium/test/utils/test_dataset_map_param_context.py
- toolium/utils/dataset.py
So far....
Expressions starting with CONTEXT let us select elements saved in context or context.storage like
```
[CONTEXT:a.b.c] returns the 'c' property of the 'b' property of the 'a' element in the context
```
recently, the index in arrays was added, so that
```
[CONTEXT:a.1.b] returns the 'b' property of the element with index 1 in the 'a' array
```
Now...
let's go a bit deeper and let's have a mechanism of selecting elements in an array of dictionaries by searching for an specific key, like this:
having this next structure saved in the context
```json
{
"the_array": [
{
"id": "first-element",
"text": "The value of the first element"
},
{
"id": "second-element",
"text": "The value of the second element"
}
]
}
```
we are now able to select like …
> NOV-244340: expression for selecting in an array for a context storage

- setup.py
Include playwright module on setup.py
> chore: include playwright module on setup

- CHANGELOG.rst
- toolium/behave/env_utils.py
- toolium/test/behave/test_env_utils.py
fix: dynamic environment error output for a feature with:
* action before the feature with error in step
* with background
Current output scenarios without failure because `background` is not updated with fail status and this lead to false positives for scenarios:
```shell
0 features passed, 1 failed, 0 skipped
0 scenarios passed, 0 failed, 0 skipped, **2 untested**
0 steps passed, 2 failed, 0 skipped, 0 undefined, 2 untested
```
Scenarios with background fail because actions before the feature fails, console log:
```shell
0 features passed, 1 failed, 0 skipped
0 scenarios passed, **2 failed**, 0 skipped
0 steps passed, 2 failed, 0 skipped, 0 undefined
```
To generate correct report xml output:
```xml
<testsuite name="1_fail.Fail feature with a single scenario" tests="2" errors="2" …
```
> bug(QAWTO-212): fix result for action before the feature error with background

- .gitignore
- CHANGELOG.rst
- requirements.txt
- toolium/test/utils/test_dataset_map_param_context.py
- toolium/test/utils/test_dataset_replace_param.py
- toolium/utils/dataset.py
- Allow negative indexes for list elements in context searches. Example: [CONTEXT:element.-1]
- Add support for JSON strings to the `DICT` and `LIST`` replacement. Example: [DICT:{"key": true}], [LIST:[null]]
- Add `REPLACE` replacement, to replace a substring with another. Example: [REPLACE:[CONTEXT:some_url]::https::http]
- Add `TITLE` replacement, to apply Python's title() function. Example: [TITLE:the title]
- Add `ROUND` replacement, float number to a string with the indicated number of decimals. Example: [ROUND:3.3333::2]
> feat: improve and add new replacements to the dataset module

- CHANGELOG.rst
- toolium/visual_test.py
When working with jpg baselines, it is not rightly saved the diff file because of not replacing anything when creating the diff file name.
This way it will work for png and jpg.
> feat: allow to save a jpg diff file in gui step

- CHANGELOG.rst
- toolium/behave/env_utils.py
Se ha detectado que cuando se usaba # en los valores de una tabla declarada en el actions before the feature, lo que había a continuación se eliminaba. Esta PR soluciona eso. Puede verse un ejemplo en el parametro description, todo lo que va a continuación de # era eliminado
```
Actions Before The Feature:
Given I create a personal purpose using the following params as client "[ENV:BAIKAL_AUTH_CLIENT]"
| param_name   | param_value                                                          |
| id           | qa_[CONTEXT:feature_name]_purpose_contract                           |
| lawful_basis | contract                                                             |
| title        | qa_[CONTEXT:feature_name]_purpose_contract                           |
| description  | …
```
> Fix row parsing when there is a #

- CHANGELOG.rst
- README.rst
- docs/bdd_integration.rst
- docs/browser_configuration.rst
- docs/driver_configuration.rst
- docs/mobile_configuration.rst
- docs/page_objects.rst
- docs/playwright_configuration.rst
- docs/toolium.pageelements.playwright.rst
- docs/toolium.pageelements.rst
- toolium/test/conf/properties.cfg
Branch documentation is deployed in https://toolium.readthedocs.io/en/feat-playwright_doc/index.html
> feat: add documentation for playwright integration

- docs/bdd_integration.rst
Siguiendo con la tarea de mover la documentación de data tags de toolium-telefonica a toolium, donde está ahora la funcionalidad. Se acutaliza bdd_integration.rst, que ya contenía una parte de la documentación de data tags, con el resto de información que sólo estaba en toolium-telefonica
> chore: update data tags documentation

- toolium/utils/dataset.py
Fix exec/locals incompatibility with Python 3.13 by using explicit exec environment
Python 3.13 no longer guarantees that variables created via exec() are visible in locals(),
so replaced usage of locals()['exec_param'] with an explicit namespace dictionary passed to exec().
This ensures compatibility across Python versions and avoids runtime errors.
> Update dataset.py for Python 3.13 

- CHANGELOG.rst
- toolium/driver_wrapper.py
- toolium/test/utils/test_driver_utils.py
- toolium/utils/driver_utils.py
We need to adapt toolium for latest versions of XCUITest and UIAutomator2 as some methods have been deprecated
Related PRs
- Toolium-telefonica: https://github.com/Telefonica/toolium-telefonica/pull/972
- Ansible config for MAC: https://github.com/Telefonica/qacdo-mac-ansible/pull/51
- Updated WDA with v10: https://github.com/Telefonica/qacdconovum-web-driver-agent/pull/28
[Tasks]
- [Appium 2.0 Migration Guide](https://appium.io/docs/en/latest/guides/migrating-1-to-2/)
- [UIAutomator2 Driver Gestures](https://github.com/appium/appium-uiautomator2-driver#mobile-gestures)
- [XCUITest Driver Mobile Commands](https://github.com/appium/appium-xcuitest-driver#mobile-commands)
- [W3C Actions API](https://www.w3.org/TR/webdriver/#actions)
```
Total Tests: 686
✅ Passed:   686 (100%)
❌ Failed:   0 …
```
> chore: Update toolium for XCUITest v9 and UIAutomator2 v4
