Telefonica/toolium

CHANGELOG.rst, requirements.txt, requirements_dev.txt, toolium/behave/environment.py, toolium/config_driver.py, toolium/driver_wrapper.py, toolium/test/conf/api-properties.cfg, toolium/test/test_driver_wrapper.py, toolium/utils.py, toolium/visual_test.py
Add Appium 1.5 support and fix minor issues
=> Fix/appium 1.5

CHANGELOG.rst, docs/bdd_integration.rst, toolium/behave/env_utils.py, toolium/behave/environment.py
Change-Id: I2edccfe9474b3bb5f00ae021d6839311f7808809
The associated example is in https://github.com/Telefonica/toolium-examples/blob/master/web_behave/features/dyn_environment_test.feature
=> [FEATURE] dynamic environment

README.rst, docs/bdd_integration.rst, docs/driver_configuration.rst, docs/reuse_driver.rst
* Include `reuse_driver` property documentation
* Update REAME sections
=> doc: include reuse_driver property documentation

toolium/config_driver.py
- Firefox & Chrome: Support to headless mode
- Firefox: Support to extra arguments
=> Headless mode and extra arguments for Firefox

toolium/behave/environment.py, toolium/driver_wrapper.py, toolium/driver_wrappers_pool.py, toolium/format_utils.py, toolium/test/test_format_utils.py, toolium/utils.py, toolium/visual_test.py
Added a method to generate valid filenames. 
It was used in every needed place before saving an image or a video to disk.
=> Feat: normalize filenames

CHANGELOG.rst, toolium/behave/env_utils.py, toolium/pageelements/page_element.py
=> [FIX] in dyn env and the scroll_element_into_view

CHANGELOG.rst, toolium/behave/env_utils.py
=> [IMPROVE] replace the \n in print by console (pretty)

CHANGELOG.rst, toolium/behave/env_utils.py
Change-Id: I7eb73d3e20fb9c2b746935c5205218a2b0899706
@rgonalo
=> [ADD] raise exception in error case

CHANGELOG.rst, toolium/driver_wrappers_pool.py, toolium/selenoid.py
Change-Id: I687c11a4a0ae4106d132340fab72afa585364f49
@rgonalo
=> [FEATURE] downloads in Selenoid

CHANGELOG.rst, toolium/selenoid.py
Change-Id: Id90c1a4b0320944a866bc98b0399ca2ae618ae6a
@rgonalo
=> [FEATURE] Check GGR session

CHANGELOG.rst, toolium/driver_wrapper.py, toolium/driver_wrappers_pool.py, toolium/path_utils.py, toolium/selenoid.py, toolium/test/test_path_utils.py, toolium/utils.py, toolium/visual_test.py
Add *makedirs_safe* method to create a new folder.
=> Fix concurrent folder creation

toolium/pageelements/page_elements.py
This is a shortcut to not putting (...).page_elements all the time
=> feat(magic-methods): expand PageElements magic methods

toolium/utils.py
I find that driver.implicitly_wait(0) could be time consumer when config.get_optional('Driver', 'implicitly_wait') equals 0, so i suggest this change. 
But theres more, while testing hybrid apps on android, and driver switch to any context "WEBVIEW", driver.implicitly_wait(0) raises Exception. My workarround now is to set implicitly_wait: 0 in properties and mock _wait_until() with the code of the commit
=> feat(utils): improve efficiency of wait until method

CHANGELOG.rst, toolium/pageelements/group_page_element.py, toolium/pageelements/page_element.py, toolium/test/pageelements/test_page_element.py
Fix automatic context selection for group element
=> Fix automatic context selection for group element

docs/page_objects.rst
Documentation about functionality to manage multitple webviews in mobile devices.
=> doc_manage_multiple_webviews_in_mobile_devices

CHANGELOG.rst, toolium/pageelements/input_text_page_element.py
Implement get text for InputText element for mobile tests
=> NOV-225986 get text in inputtext for mobile

CHANGELOG.rst, toolium/test/utils/test_dataset_utils.py, toolium/utils/dataset.py
Param [TIMESTAMP] to generate timestamp value  of the actual moment
=> feat: add timestamp to be used as param [TIMESTAMP]

CHANGELOG.rst, docs/driver_configuration.rst, docs/driver_configuration_modification.rst
Previous version:
New version:
=> fix: update driver configuration doc to fix indent error

CHANGELOG.rst, docs/bdd_integration.rst, toolium/test/utils/test_dataset_replace_param.py, toolium/utils/dataset.py
Added v4 UUID as a param replacement, which surprisingly was not there yet.
=> feat: add UUID param replacement

toolium/pageelements/page_element.py
Otherwise index out of bounds error happens
=> fix: validate that there are pages in context dict before accessing

toolium/config_driver.py, toolium/test/test_config_driver.py
Pass executable_path through Service object and remove Opera and PhantomJS compatibility.
=> task: update executable path and remove opera and phantomjs

toolium/config_driver.py, toolium/test/test_config_driver.py
Changed headless option on chrome from --headless to --headless=new.
--headless < chrome v96
--headless=chrome v96 - v108
--headless=new >=v109
=> changed chrome --headless option to --headless=new

toolium/driver_wrapper.py
Playwright: enable headless mode from configuration files
=> feat: playwright enable headless config
